# Generated by Django 5.0.1 on 2024-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professional_experiences',
            field=models.ManyToManyField(blank=True, null=True, to='core.professionalexperience'),
        ),
    ]
