# Generated by Django 5.0.1 on 2024-02-26 13:42

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_resumetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('work_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(blank=True, max_length=20)),
                ('github', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='education',
            old_name='institution',
            new_name='institution_name',
        ),
        migrations.RenameField(
            model_name='resumetemplate',
            old_name='design',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='github_profile',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='education',
            name='field_study',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='job_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('educations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_educations', to='core.education')),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.personalinformation')),
                ('professional_experiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experiences', to='core.professionalexperience')),
                ('professional_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_summary', to='core.professionalsummary')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='core.project')),
                ('selected_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resumetemplate')),
                ('skills', models.ManyToManyField(blank=True, to='core.skill')),
                ('socials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_socials', to='core.socials')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
