# Generated by Django 5.0.1 on 2024-02-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professionalexperience_professionalsummary_socials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='position_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='professional_experiences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AddField(
            model_name='user',
            name='educations',
            field=models.ManyToManyField(related_name='user_educations', to='core.education'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_experiences',
            field=models.ManyToManyField(blank=True, to='core.professionalexperience'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(related_name='user_projects', to='core.project'),
        ),
    ]
