# Generated by Django 5.0.1 on 2024-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_professionalexperience_position_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
